service: ${self:custom.service}

custom:
  profile: perfsys
  service: ${file(./config.json):service}
  stage: ${opt:stage, '${file(./config.json):stage}'}
  region: ${opt:region, '${file(./config.json):region}'}
  reportsTableName: ${self:service}-${opt:stage, '${file(./config.json):stage}'}-reports
  officeActivityTableName: ${self:service}-${self:custom.stage}-officeActivity

provider:
  name: aws
  profile: perfsys
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource:
        - { "Fn::GetAtt": ["reportsTable", "Arn" ] }
        - { "Fn::GetAtt": ["officeActivityTable", "Arn" ] }
  environment:
    REPORTS_TABLE_NAME: ${self:custom.reportsTableName}
    OFFICE_ACTIVITY_TABLE_NAME: ${self:custom.officeActivityTableName}


functions:
  saveSalesReport:
    handler: index.handler
    events:
      - http:
          path: /reports
          method: POST
          cors: true

  saveOfficeActivity:
    handler: index.handler
    events:
      - http:
          path: /activity
          method: POST
          cors: true
#  getReports:
#    handler: index.handler
#    events:
#      - http:
#          path: /reports
#          method: GET
#          cors: true

resources:
  Resources:
    reportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.reportsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    officeActivityTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.officeActivityTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
