service: ${self:custom.service}

custom:
  service: ${file(./config.json):service}
  stage: ${opt:stage, '${file(./config.json):stage}'}
  region: ${opt:region, '${file(./config.json):region}'}
  reportsTableName: ${self:service}-${file(./config.json):reportsTableName}-${opt:stage, '${file(./config.json):stage}'}

provider:
  name: aws
  profile: perfsys
  runtime: nodejs10.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource:
        - { "Fn::GetAtt": ["reportsTable", "Arn" ] }
  environment:
    REPORTS_TABLE_NAME: ${self:custom.reportsTableName}


functions:
  postReport:
    handler: index.handler
    events:
      - http:
          path: /reports
          method: POST
          cors: true

#  getReports:
#    handler: index.handler
#    events:
#      - http:
#          path: /reports
#          method: GET
#          cors: true

resources:
  Resources:
    reportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.reportsTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
