service: cloud-reports
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource:
        - "arn:aws:dynamodb:eu-central-1:879430108267:table/reports"
functions:
  # getPerson:
  #   handler: handler.getPerson
  #   events:
  #     - http:
  #         path: persons/{id}
  #         method: GET
    

  postReport:
    handler: handler.postReport
    events:
      - http:
          path: reports
          method: POST

  getReports:
    handler: handler.getReports
    events:
      - http:
          path: /reports
          method: GET

    resources:
      Resources:
        # uploadBucket:
        #   Type: AWS::S3::Bucket
        #   Properties:
        #     BucketName: ${self:service}-${self:provider.stage}-uploads

        reportsTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: reports
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1