service: cloud-reports
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource:
        - { "Fn::GetAtt": ["reportsTable", "Arn" ] }
functions:
  # getPerson:
  #   handler: handler.getPerson
  #   events:
  #     - http:
  #         path: persons/{id}
  #         method: GET
    

  postReport:
    handler: index.handler
    events:
      - http:
          path: reports
          method: POST
          cors: true

  getReports:
    handler: index.handler
    events:
      - http:
          path: /reports
          method: GET
          cors: true

resources:
  Resources:
    # uploadBucket:
    #   Type: AWS::S3::Bucket
    #   Properties:
    #     BucketName: ${self:service}-${self:provider.stage}-uploads

    reportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName:  ${self:service}-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1